### ISSUE TITLE
Android 7.0 support?

### ISSUE THREAD

**Issue by winardi93** [orhanobut/hawk#160]
hi i'm using a Nexus 5X running the latest android 7.0, but somehow all the value returned all nulls. When i tried using other phones it works fine, on genymotion also it returns the expected value from what i put. Can you guys help confirm this?

**Comment by pedronveloso** [comment]
I've reported this issue a while back: https://github.com/orhanobut/hawk/issues/155

It basically happens if the phone had a version of Android previous to Android 7 installed, and then the OS updates. If you uninstall the app and install again from scratch everything works. It most likely has to do with the changes at platform level, but it would be great if the library could handle this.

**Comment by winardi93** [comment]
@pedronveloso  thank you for the quick response i tried what you recommended and now the app works fine, yesterday i though it was due to android's latest security patch so hawk need to implement the new security method
