### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by orhanobut** [orhanobut/hawk#3]
Instead of reading all values from the file, it would be nice to cache and reuse it. It will give a good performance hit.

**Comment by fncapps** [comment]
In some cases, when I try to get more than one or two values from Hawk the app work really slow. So it would be really nice to have this performance hit. :+1:

**Comment by orhanobut** [comment]
@fncapps Thank you for the feedback! I was wondering about the speed issues and it's great to know that we need improvement. I'm currently making a benchmark test in the terms of speed and space. I'll add this cache system for sure as an optional.

**Comment by orhanobut** [comment]
@fncapps Can you try with the new version please? We've made a major change for the speed.

**Comment by fncapps** [comment]
I've just tried it, and I'm having some problems with it. Just to be sure, should I make ``Hawk.init(Context, String)`` in each class I'm using it or just with one init in the whole app would be enough?

**Comment by orhanobut** [comment]
just one init would be enough, the best approach would be to make it in the class that you extend from Application

**Comment by fncapps** [comment]
Wow, now the speed is great, you don't really notice that an encryption algorithm is working behind some actions. I really appreciate the effort @orhanobut!

Just for anyone that could have the problem I had: If you had some Hawk keys saved in a phone/emulator with version 1.3 and you try to read them after changing to version 1.4, the app crashes. I think it is due to the **password** you've introduced in 1.4 version.

By the way, should this **password** for the algorithm be configured by the user or set programmatically by the developer?

**Comment by kardeslik** [comment]
@fncapps Best practise for password is getting it from user directly or generating it by user entered data. But in that case either user will enter that value every time app is used or you must store it securely.
You can also set it programmatically, but in that case you should not put that password as constant string in the code because attacker can get that string by reverse engineering. For that case, best practice is creating the password on-the-fly.

**Comment by orhanobut** [comment]
Cache won't be added, since the speed is quite enough.
