### ISSUE TITLE
How does it Work??

### ISSUE THREAD

**Issue by syedalinaqi** [orhanobut/hawk#46]
Well u see if I use `Hawk.put(key, T);` in `onCreate()` method and I change its value  afterwards then again if the activity is started, Will its Value change??

**Comment by syedalinaqi** [comment]
Also Can it be used to store data of about 24000 Records. If no then is there any other way???

**Comment by orhanobut** [comment]
1. Whenever you call Hawk.put(), yes it will change the current value.
2. Hawk uses sharedpreferences as storage at the background, since it uses xml files to save/read, I don't think it is good idea to save 24000 records. But this is just assumption, I never did any benchmark or checked the pros/cons. 
3. Another storage approach could be implemented in order to have good performance for the huge size

**Comment by syedalinaqi** [comment]
hmm so... if I use the code `Hawk.put()` in `onCreate()` Method then it will change the value of the key on every start. For example:
`public void onCreate (savedinstance ....){`
`          setContentView(...);`
`          Hawk.put(INT_KEY, 1);`
``
`}`

then on another method in the activity
`public void otherMethod(){`
`          Hawk.put(INT_KEY, 2);`
`}`

SO will it change the value of the `INT_KEY` on every Start??? If Yes, then how can i Prevent IT... Shoud i use a `If.....else` statement????

**Comment by orhanobut** [comment]
Use Hawk.contains(INT_KEY) onCreate to check whether you already set it or not.

**Comment by syedalinaqi** [comment]
hmm... k thanks....
