### ISSUE TITLE
How to check password is correct?

### ISSUE THREAD

**Issue by KagayamaKaede** [orhanobut/hawk#90]
I follow below step:
1. Init Hawk in password A.
2. Change password in code and recompile app.
3. Start app and init Hawk.

Finally,Hawk not call onFail. so, how to check password is correct?

**Comment by orhanobut** [comment]
There is no option to check the previous password, if you change the password, Hawk cannot differentiate it, thus all the previous data will be lost, You need to make sure that it's the same password and it is not changed.

**Comment by KagayamaKaede** [comment]
Why hawk don't check password correct?

In many case,password stored separately is not better.

In the future,Can you add this functionality?

**Comment by orhanobut** [comment]
Basically we don't want to keep this information in somewhere, in order to know the difference between new and old, we need to keep it somewhere and that means we will expose this data. Password requirement is completely up to client responsibility currently. But we can discuss for other alternatives or approaches.

**Comment by KagayamaKaede** [comment]
OK, I understand, Thanks for reply!

In my previous one issue(#88), Have you forgotten the push proguard setting?
